spring.application.name=apigateway
spring.security.user.name=user
spring.security.user.password=password
spring.datasource.url= jdbc:postgresql://localhost:5432/rayen1
spring.datasource.password=newpassword
spring.datasource.username=postgres

